// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drzylxvkadmjwocfivgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyenlseHZrYWRtandvY2Zpdmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTI1MzQsImV4cCI6MjA1OTQ4ODUzNH0.9x5JEzRbNiKitjhDRqkKqapw5ChpOb3m7WJPzNRi_-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);